export const quotes = [
    {
        quote: "Didn't ask for a dime. Two dollars.",
        character: "The Paperboy",
        source: "Better Off Dead",
        url: "https://www.youtube.com/watch?v=FsxJfcFVnpo",
    },
    {
        quote: "Show me the money!",
        character: "Rod Tidwell",
        source: "Jerry Maguire",
        url: "https://www.youtube.com/watch?v=IpwSXWq1wwU",
    },
    {
        quote: "Where's the money, Lebowski?",
        character: "Woo",
        source: "The Big Lebowski",
        url: "https://www.youtube.com/watch?v=9X_Ne3S5FAU",
    },
    {
        quote: "You'll get nothing, and like it.",
        character: "Judge Smails",
        source: "Caddyshack",
        url: "https://www.youtube.com/watch?v=0f6l1QljpMo",
    },
    {
        quote: "We're doing it for a shitload of money!",
        character: "Lone Starr",
        source: "Spaceballs",
        url: "https://www.youtube.com/watch?v=aGWRAa5uTUQ",
    },
    {
        quote: "There's only one thing I like better. Other people's money.",
        character: "Lawrence Garfield",
        source: "Other People's Money",
        url: "https://www.youtube.com/watch?v=lUJTRqV7B8E",
    },
    {
        quote: "In a sluggish economy, never, ever, fuck with another man's livelihood.",
        character: "Guido",
        source: "Risky Business",
        url: "https://www.youtube.com/watch?v=I5cS0_op1IE",
    },
    {
        quote: "So I'm talking about fractions of a penny here. Over time they add up to a lot.",
        character: "Peter Gibbons",
        source: "Office Space",
        url: "https://www.youtube.com/watch?v=yZjCQ3T5yXo",
    },
    {
        quote: "You're right Mr. Thatcher. I did lose a million dollars last year.",
        character: "Charles Foster Kane",
        source: "Citizen Kane",
        url: "https://www.youtube.com/watch?v=tzhb3U2cONs",
    },
    {
        quote: "There's only one thing I like better than money. Revenge.",
        character: "Lola",
        source: "Shark Tale",
        url: "https://www.youtube.com/watch?v=PyypLt2m0EY",
    },
    {
        quote: "Why does that name ring a bell? - I don't know. Maybe we owe him money?",
        character: "Pain & Panic",
        source: "Hercules",
        url: "https://www.youtube.com/watch?v=y-9f5Z1bCSg",
    },
    {
        quote: "I'm just asking for an eightball and two million dollars.",
        character: "Baby Billy Freeman",
        source: "The Righteous Gemstones",
        url: "https://www.youtube.com/watch?v=RBAP14Fz2AU",
    },
    {
        quote: "That's what the money is for!",
        character: "Don Draper",
        source: "Mad Men",
        url: "https://www.youtube.com/watch?v=BnNV4_8izkI",
    },
    {
        quote: "Here it is, all of it in cash.",
        character: "Matt Jamison",
        source: "The Leftovers",
        url: "https://www.youtube.com/watch?v=aMzP2l3bPBk",
    },
    {
        quote: "Based on what we stole plus interest, how much does everybody owe?",
        character: "Danny Ocean",
        source: "Ocean's Twelve",
        url: "https://www.youtube.com/watch?v=L-jHeNFuBsQ",
    },
    {
        quote: "I've been goin' over my markers. You're into me for five grand.",
        character: "Sykes",
        source: "Shark Tale",
        url: "https://www.youtube.com/watch?v=mV_aZNMjb1I",
    },
    {
        quote: "Well, why you do it then, Baby Billy? Well, 'cause I'm selfless.",
        character: "Baby Billy Freeman",
        source: "The Righteous Gemstones",
        url: "https://www.youtube.com/watch?v=dD2WT8SeOSw",
    },
    {
        quote: "You can't just say the word bankruptcy and expect anything to happen.",
        character: "Oscar Martinez",
        source: "The Office",
        url: "https://www.youtube.com/watch?v=EuZeff2y32M",
    },
    {
        quote: "You owe me 100 g's! And you can make the check out, to Greendale.",
        character: "Pierce Hawthorne",
        source: "Community",
        url: "https://www.youtube.com/watch?v=m3kL68-P6JQ",
    },
    {
        quote: "There's always money in the banana stand!",
        character: "George Bluth Sr.",
        source: "Arrested Development",
        url: "https://www.youtube.com/watch?v=zsxdrHgyJtc",
    },
    {
        quote: "You owe me restitution!",
        character: "Lucy Van Pelt",
        source: "It's the Great Pumpkin, Charlie Brown",
        url: "https://www.youtube.com/watch?v=y09b2Rb6lJI",
    },
    {
        quote: "She's old. You can't just take her stuff. She's too old.",
        character: "Happy Gilmore",
        source: "Happy Gilmore",
        url: "https://www.youtube.com/watch?v=Y1AtU4JfTbo",
    },
    {
        quote: "I don't have any cash, but I do have the pink slip to my car.",
        character: "Brian O'Conner",
        source: "The Fast and the Furious",
        url: "https://www.youtube.com/watch?v=rHKc9SMqXZU",
    },
];
